model:
  model_name: "HuggingFaceFW/ablation-model-fineweb-v1"
  model_max_length: 2048
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  tokenizer_pad_token: "<|endoftext|>"
  load_pretrained_weights: False
  trust_remote_code: True

data:
  train:
    datasets:
      - dataset_name: "HuggingFaceFW/fineweb-edu"
        subset: "default" # 1.3B examples, 1.3T tokens
        split: "train"
      # Polaris copy of the dataset:
      # - dataset_name: "/eagle/community_ai/datasets/fineweb-edu/sample-10BT"
      #   subset: "default"
      #   split: "train"
    stream: True
    pack: True
    target_col: "text"
    use_async_dataset: True

training:
  trainer_type: "TRL_SFT" # or OUMI
  save_steps: 500
  # If gradient checkpointing is enabled: use 12 (~94% of 40GB VRAM)
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 8

  enable_gradient_checkpointing: False
  gradient_checkpointing_kwargs:
    use_reentrant: False
  ddp_find_unused_parameters: False
  optimizer: "adamw_torch_fused"
  compile: True

  lr_scheduler_type: "cosine_with_min_lr"
  lr_scheduler_kwargs:
    min_lr: 0.6e-4 # 2x that in paper since we have 4x more GPUs
  learning_rate: 0.6e-3 # 2x that in paper since we have 4x more GPUs
  warmup_steps: 500
  weight_decay: 0.1

  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 32

  logging_steps: 10
  log_model_summary: False
  output_dir: "/eagle/community_ai/wizeng/models/20241223_fineweb"
  include_performance_metrics: True
  enable_wandb: True
