# Emre's Lora config for Llama 8B.

model:
  model_name: "meta-llama/Llama-3.1-8B-Instruct"
  model_max_length: 4096
  attn_implementation: "sdpa"
  trust_remote_code: True
  tokenizer_pad_token: "<|finetune_right_pad_id|>"
  enable_liger_kernel: True

data:
  train:
    datasets:
      - dataset_name: "text_sft_jsonl"
        # 308,522 examples
        dataset_path: "../experiment7-snips_sgd_masking_toolace-train.jsonl"
        # 311,639 examples
        # dataset_path: "experiment7-snips_sgd_masking_toolace.json"
        # 1k examples
        # dataset_path: "experiment7-snips_sgd_masking_toolace-1k.jsonl"
    target_col: "text"
    use_async_dataset: True
  validation:
    datasets:
      - dataset_name: "text_sft_jsonl"
        # 3117 examples
        dataset_path: "../experiment7-snips_sgd_masking_toolace-val.jsonl"
    target_col: "text"
    use_async_dataset: True

training:
  trainer_type: "TRL_SFT"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 2

  per_device_eval_batch_size: 1
  eval_strategy: steps
  eval_steps: 500
  try_resume_from_last_checkpoint: True

  mixed_precision_dtype: "BF16"
  # optimizer: "adamw_torch"
  optimizer: "adamw_torch_fused"
  learning_rate: 1.0e-04
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.1
  use_peft: True

  enable_gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  ddp_find_unused_parameters: False
  dataloader_num_workers: "auto"
  # dataloader_num_workers: 16
  dataloader_prefetch_factor: 32
  empty_device_cache_steps: 50
  save_epoch: True
  save_steps: 500
  logging_steps: 10
  enable_wandb: True
  run_name: "Llama-3.1-8B-Instruct-experiment7"
  include_performance_metrics: True
  output_dir: "/gcs_dir/wizeng/models/20210107_emre_8b_allloralayers"

peft:
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.0
  lora_target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
