# Class: oumi.core.configs.TrainingConfig
# https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/training_config.py

##
# LoRA config for sft-training Llama-90B-Vision with the vqav2-small dataset.
##

model:
  model_name: "meta-llama/Llama-3.2-90B-Vision-Instruct"
  torch_dtype_str: "bfloat16"
  model_max_length: 512
  attn_implementation: "sdpa"
  chat_template: "llama3-instruct"
  freeze_layers:
    - "vision_model"

data:
  train:
    collator_name: "vision_language_with_padding"
    experimental_use_torch_datapipes: True
    datasets:
      - dataset_name: "merve/vqav2-small"
        split: "validation"
        shuffle: True
        seed: 42
        transform_num_workers: "auto"
        dataset_kwargs:
          processor_name: "meta-llama/Llama-3.2-90B-Vision-Instruct"
          limit: 2048
          return_tensors: True

training:
  output_dir: "output/vlm_finetuned"
  trainer_type: "TRL_SFT"
  enable_gradient_checkpointing: True
  use_peft: True
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  max_steps: 5 # Train for a few steps only (demonstration purposes)

  gradient_checkpointing_kwargs:
    # Reentrant docs: https://pytorch.org/docs/stable/checkpoint.html#torch.utils.checkpoint.checkpoint
    use_reentrant: False
  ddp_find_unused_parameters: False
  empty_device_cache_steps: 1
  compile: False

  optimizer: "adamw_torch_fused"
  learning_rate: 2e-5
  warmup_ratio: 0.03
  weight_decay: 0.0
  lr_scheduler_type: "cosine"

  logging_steps: 2
  save_steps: 0
  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 16
  include_performance_metrics: True
  enable_wandb: True

peft:
  q_lora: False
  lora_r: 16
  lora_alpha: 16
  lora_dropout: 0
  lora_target_modules:
    - "q_proj"
    - "v_proj"
    - "o_proj"
    - "k_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  init_lora_weights: DEFAULT

fsdp:
  enable_fsdp: True
  mixed_precision: "bf16"
  sharding_strategy: "FULL_SHARD"
  forward_prefetch: "BACKWARD_POST"
  auto_wrap_policy: "TRANSFORMER_BASED_WRAP"
  transformer_layer_cls: "MllamaSelfAttentionDecoderLayer,MllamaCrossAttentionDecoderLayer,MllamaVisionEncoderLayer"
