# Lora config for Llama 70B.
# Borrows param values from:
# https://github.com/pytorch/torchtune/blob/main/recipes/configs/llama3_1/70B_lora.yaml

model:
  model_name: "meta-llama/Llama-3.3-70B-Instruct"
  model_max_length: 4096
  attn_implementation: "sdpa"
  trust_remote_code: True
  tokenizer_pad_token: "<|finetune_right_pad_id|>"
  enable_liger_kernel: True

data:
  train:
    datasets:
      - dataset_name: "text_sft_jsonl"
        # 308,522 examples
        dataset_path: "/home/wizeng/experiment7-snips_sgd_masking_toolace-train.jsonl"
        # 311,639 examples
        # dataset_path: "experiment7-snips_sgd_masking_toolace.json"
        # 1k examples
        # dataset_path: "experiment7-snips_sgd_masking_toolace-1k.jsonl"
    target_col: "text"
    use_async_dataset: True
  validation:
    datasets:
      - dataset_name: "text_sft_jsonl"
        # 3117 examples
        dataset_path: "/home/wizeng/experiment7-snips_sgd_masking_toolace-val.jsonl"
    target_col: "text"
    use_async_dataset: True

training:
  trainer_type: "TRL_SFT"
  use_peft: True
  save_epoch: True
  save_steps: 100
  num_train_epochs: 3
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 1

  per_device_eval_batch_size: 1
  eval_strategy: steps
  eval_steps: 500
  try_resume_from_last_checkpoint: True

  mixed_precision_dtype: "BF16"
  enable_gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  ddp_find_unused_parameters: False
  optimizer: "adamw_torch_fused"
  warmup_ratio: 0.1
  learning_rate: 3.0e-04
  compile: False

  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 32

  logging_steps: 10
  log_model_summary: False
  empty_device_cache_steps: 50
  output_dir: "output/llama70b.lora"
  include_performance_metrics: True
  enable_wandb: True

peft:
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.0
  lora_target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj

fsdp:
  enable_fsdp: True
  forward_prefetch: True
  auto_wrap_policy: "TRANSFORMER_BASED_WRAP"
  transformer_layer_cls: "LlamaDecoderLayer"
