model:
  model_name: "meta-llama/Llama-3.2-11B-Vision-Instruct"
  torch_dtype_str: "bfloat16"
  model_max_length: 1024
  attn_implementation: "sdpa"
  chat_template: "llama3-instruct"
  freeze_layers:
    - "vision_model"

data:
  train:
    collator_name: "vision_language_with_padding"
    use_torchdata: True  # Train error appears *even* if False

    datasets:
      - dataset_name: "HuggingFaceM4/the_cauldron"
        split: "train"
        subset: "geomverse"
        shuffle: True
        seed: 42
        transform_num_workers: "auto"
        trust_remote_code: True # seems necessary
        sample_count: 100
        dataset_kwargs:
          processor_name: "meta-llama/Llama-3.2-11B-Vision-Instruct"
          return_tensors: True
          # limit: 100

training:
  output_dir: "temp_cauldron_train"
  trainer_type: "TRL_SFT"
  enable_gradient_checkpointing: True
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 2
  use_peft: True
  max_steps: 2

  gradient_checkpointing_kwargs:
    # Reentrant docs: https://pytorch.org/docs/stable/checkpoint.html#torch.utils.checkpoint.checkpoint
    use_reentrant: False
  ddp_find_unused_parameters: False
  empty_device_cache_steps: 1

  optimizer: "adamw_torch_fused"
  learning_rate: 2e-5
  warmup_ratio: 0.03
  weight_decay: 0.0
  lr_scheduler_type: "cosine"

  logging_steps: 5
  save_steps: 0
  dataloader_main_process_only: False
  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 16
  include_performance_metrics: True
  enable_wandb: True

peft:
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  lora_target_modules:
    - "q_proj"
    - "v_proj"
    - "o_proj"
    - "k_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  lora_init_weights: GAUSSIAN
