name: llava-7b-sft

num_nodes: 1 # Set it to N for multi-node training.

resources:
  accelerators: { "A100": 4 }
  any_of:
    - use_spot: true
    - use_spot: false
  disk_size: 500 # Disk size in GBs

# Upload working directory to remote ~/sky_workdir.
workdir: .

# Mount local files.
file_mounts:
  ~/.netrc: ~/.netrc # WandB credentials

envs:
  WANDB_PROJECT: oumi-train
  OUMI_RUN_NAME: llava.7b.sft
  ACCELERATE_LOG_LEVEL: info
  TOKENIZERS_PARALLELISM: false

setup: |
  set -e
  pip install uv && uv pip install '.[gpu]'
  # Install model from HF Hub. This tool increases download speed compared to
  # downloading the model during training.
  pip install hf_transfer
  HF_HUB_ENABLE_HF_TRANSFER=1 huggingface-cli download llava-hf/llava-1.5-7b-hf

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  set -x  # Print "torchrun" command with expanded variables
  accelerate launch \
      --num_machines ${OUMI_NUM_NODES} \
      --machine_rank ${SKYPILOT_NODE_RANK} \
      --num_processes ${OUMI_TOTAL_NUM_GPUS} \
      --main_process_ip ${OUMI_MASTER_ADDR} \
      --main_process_port 8007 \
      --use_fsdp \
      --config_file configs/examples/vision/llava_7b/accelerate.yaml \
      -m oumi.train \
      -c configs/examples/vision/llava_7b/sft_train.yaml \
      "training.run_name='${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}'" \
      "training.max_steps=20" \
      "training.save_steps=0" \
      "training.save_final_model=false" \
      "training.per_device_train_batch_size=2" \
      "training.gradient_accumulation_steps=4" \
      "training.enable_gradient_checkpointing=False"

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"


#  4 GPUS
#  sky launch -i 10 --env OUMI_RUN_NAME=llava.7b.sft.vqav2-small.frozen-vision.4xA10040GB.20steps.bs2.gas4.noprefetch.cpuoffload.v101 --cloud GCP --use-spot --num-nodes 1 --gpus "A100:4" --cluster xrdaukar-1node4gpu-01-lema-cluster ./configs/examples/vision/llava_7b/sky_fsdp_job.yaml
#
#  fsdp_forward_prefetch: false bs=2, gas=4, TRL_SFT, fsdp_offload_params: true  https://wandb.ai/lema-train-test/oumi-train/runs/0ecfqed1
#  train_samples_per_second': 1.073, 'train_steps_per_second': 0.034, 'train_tokens_per_second': 274.638,

#  fsdp_forward_prefetch: true bs=2, gas=4, TRL_SFT, fsdp_offload_params: true https://wandb.ai/lema-train-test/oumi-train/runs/rwdcq2se
# 'train_samples_per_second': 1.073, 'train_steps_per_second': 0.034, 'train_tokens_per_second': 274.719,

# SIZE_BASED_WRAP 10M
