# Emre's Lora config for Llama 70B.
# Borrows param values from:
# https://github.com/pytorch/torchtune/blob/main/recipes/configs/llama3_1/70B_lora.yaml
# https://github.com/pytorch/torchtune/blob/main/recipes/configs/llama3_1/405B_qlora.yaml

model:
  model_name: "meta-llama/Llama-3.3-70B-Instruct"
  model_max_length: 4096
  attn_implementation: "sdpa"
  trust_remote_code: True
  tokenizer_pad_token: "<|finetune_right_pad_id|>"
  enable_liger_kernel: True

data:
  train:
    datasets:
      - dataset_name: "text_sft_jsonl"
        # 308,522 examples
        dataset_path: "../experiment7-snips_sgd_masking_toolace-train.jsonl"
        # 311,639 examples
        # dataset_path: "experiment7-snips_sgd_masking_toolace.json"
        # 1k examples
        # dataset_path: "experiment7-snips_sgd_masking_toolace-1k.jsonl"
    target_col: "text"
    use_async_dataset: True
  validation:
    datasets:
      - dataset_name: "text_sft_jsonl"
        # 3117 examples
        dataset_path: "../experiment7-snips_sgd_masking_toolace-val.jsonl"
    target_col: "text"
    use_async_dataset: True

training:
  trainer_type: "TRL_SFT"
  num_train_epochs: 3
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8

  mixed_precision_dtype: "BF16"
  optimizer: "adamw_torch_fused"
  learning_rate: 5.0e-05
  use_peft: True

  per_device_eval_batch_size: 1
  eval_strategy: steps
  eval_steps: 500
  try_resume_from_last_checkpoint: True

  enable_gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  ddp_find_unused_parameters: False
  warmup_ratio: 0.1
  compile: False

  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 32

  save_epoch: True
  save_steps: 500
  logging_steps: 100
  log_model_summary: False
  empty_device_cache_steps: 50
  run_name: "Llama-3.3-70B-Instruct-experiment7"
  include_performance_metrics: True
  output_dir: "/gcs_dir/wizeng/models/20210109_emre_70b"
  enable_wandb: True

peft:
  q_lora: True
  # https://github.com/pytorch/torchtune/blob/37337f71677da69f0967a9cde34b96ad7fec3cb6/torchtune/modules/peft/lora.py#L95
  bnb_4bit_quant_type: "nf4"
  # Must use a float type for quantized data storage. See:
  # https://huggingface.co/docs/bitsandbytes/main/en/fsdp_qlora#quantized-data-storage.
  bnb_4bit_quant_storage: "bfloat16"
  bnb_4bit_compute_dtype: "bfloat16"
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.0
  lora_target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"

fsdp:
  enable_fsdp: True
  forward_prefetch: True
  auto_wrap_policy: "TRANSFORMER_BASED_WRAP"
  transformer_layer_cls: "LlamaDecoderLayer"
